Generate time series
aicers/crusher pull request #16
Opened 2022-11-15 11:22 UTC by sehkone

Assuming giganto sends events in order of time, this generates time series according to the model's configuration. Close #10

2022-11-15 20:30 UTC, msk commented
테스트 코드 추가해주세요. 테스트 내에서 서버를 띄우고 테스트하는 예는 giganto의 ingestion::tests 모듈에 있습니다.

2022-11-17 04:20 UTC, sehkone commented
> 테스트 코드 추가해주세요. 테스트 내에서 서버를 띄우고 테스트하는 예는 giganto의 ingestion::tests 모듈에 있습니다.

테스트 코드를 @BLYKIM가 작성하였습니다.

2022-11-17 20:06 UTC, msk requested changes

2022-11-17 20:06 UTC, msk commented on Cargo.toml
> +lazy_static = "1.4"
이건 테스트 코드에서만 쓰이는 것 같은데, 그렇다면 dev-dependencies에 들어가야 합니다.

2022-11-17 20:06 UTC, msk commented on src/subscribe/tests.rs
> +/// start time: 2022/11/17 00:00:00
`///`는 rustdoc이 함수 문서로 인식하는 주석입니다. 단순히 참고용 주석은 `//`를 써 주세요.

2022-11-17 20:06 UTC, msk commented on src/subscribe/tests.rs
> +// test만들다가 현재 test할 기능이 없어 쓰지 않지만
함수 정의 끝나고 다음 함수 시작하기 전에 한 줄 띄어 주세요.

2022-11-17 20:06 UTC, msk commented on src/subscribe/tests.rs
> +        println!("{:?}", time);
이건 테스트에 필요없는 것 같은데요.

2022-11-18 23:06 UTC, msk approved these changes

2022-11-18 23:06 UTC, merged