Add QUIC Connection logic
aicers/crusher pull request #3
Opened 2022-11-03 05:16 UTC by kimhanbeom

- Add QUIC Client for connection with giganto
 - Add QUIC Server for connection with request programs.

 Closes: #1, Closes: #2

2022-11-03 05:45 UTC, sehkone commented on README.md
> +* `giganto_ingestion_address`: IP address and port number of `Giganto ingestion`.
Crusher 입자에서 이 정보가 필요한가요?

2022-11-03 05:54 UTC, sehkone commented on README.md
> +* `request_address`:  Crusher's Request Server IP address and port number.
이것은 review 주소를 말하는 것인가요? 그렇다면 review_address라고 적는 게 분명할 것 같아요.

2022-11-03 05:56 UTC, sehkone commented on src/settings.rs
> +    pub request_address: SocketAddr, // IP address & port to reqeust message
주석에 오타가 있네요^^

2022-11-03 05:57 UTC, kimhanbeom commented on README.md
> +* `request_address`:  Crusher's Request Server IP address and port number.
@sehkone 
request_address 는 review와의 QUIC 통신을 하기 위한 crusher server 주소입니다. 서버를 정의한 module이 request 라서 네이밍을  위와 같이 하였습니다.

2022-11-03 05:59 UTC, kimhanbeom commented on README.md
> +* `giganto_ingestion_address`: IP address and port number of `Giganto ingestion`.
@sehkone 
quic tls 인증을 통한 connection 시 설명과 같이 이름의 매칭을 확인하기 때문에 반드시 필요합니다.

2022-11-03 06:03 UTC, kimhanbeom commented on src/settings.rs
> +    pub request_address: SocketAddr, // IP address & port to reqeust message
@sehkone 
오타 수정하겠습니다.

2022-11-03 06:05 UTC, kimhanbeom commented on README.md
> +* `giganto_ingestion_address`: IP address and port number of `Giganto ingestion`.
@sehkone 
네. time series 송신할떄 ingestion주소를 사용합니다.

2022-11-03 06:52 UTC, kimhanbeom commented on README.md
> +* `request_address`:  Crusher's Request Server IP address and port number.
@sehkone 
현재 코드는 crusher가 server로 구현되어 있어서 이에 대한 코드 수정과 issue수정 후  다시 push 하겠습니다.

2022-11-03 06:58 UTC, sehkone commented on README.md
> +* `request_address`:  Crusher's Request Server IP address and port number.
@kimhanbeom Review가 crusher에게 접속하는 것이 아니라 그 반대가 되어야 합니다.

2022-11-03 07:00 UTC, sehkone commented on README.md
> +* `request_address`:  Crusher's Request Server IP address and port number.
@kimhanbeom 아 이미 수정하고 있군요.

2022-11-04 00:05 UTC, kimhanbeom commented
client role로 수정 완료 하였습니다.

2022-11-04 09:08 UTC, kimhanbeom commented
@sehkone 
review 실행 세팅(인증서/주소)과 crusher를 맞추고 실행하여 connection 확인하였습니다.

2022-11-08 00:19 UTC, msk requested changes

2022-11-08 00:19 UTC, msk commented on src/subscribe.rs
> +        exit(0);
giganto가 리부팅 등의 이유로 잠시 handshake를 할 수 없는 경우일 수도 있으므로 그냥 종료하는 것보다는 에러를 리턴하는 것이 좋겠습니다.

2022-11-08 00:55 UTC, kimhanbeom commented
해당 사항 수정 완료했습니다.

2022-11-08 01:07 UTC, msk approved these changes

2022-11-08 01:07 UTC, merged