[WIP] Add `delete_sampling_policy` api
aicers/crusher pull request #53
Opened 2023-04-13 09:01 UTC by BLYKIM

- Remove policy in runtime policy list.
- Close channel with giganto by id.

Close: #52

2023-04-19 06:49 UTC, sehkone commented on src/request.rs
> +        close_channel_ids: Arc<RwLock<Vec<u32>>>,
이름이 혼동의 여지가 있으니 좀 더 명료하게 바꾸면 좋겠네요. 지우려는 게 policy 니까 channel 대신 policy가 나을 것 같고, runtime 보다는 active가 나을 것 같아요.

2023-04-19 06:52 UTC, sehkone commented on src/request.rs
> +        let policies_id = bincode::DefaultOptions::new()
policy_ids 가 더 적당하겠네요.

2023-04-20 01:21 UTC, syncpark requested changes

2023-04-20 01:21 UTC, syncpark commented on src/subscribe.rs
>                                  "Stream Channel Closed. Retry connection to {} after {} seconds.",
대소문자 구분 필요:
Stream Channel Closed => Stream channel closed

2023-04-20 01:21 UTC, syncpark commented on src/subscribe.rs
>          info!("Stream's Policy : {:?}", policy);
Stream's Policy => Stream's policy

2023-04-20 01:21 UTC, syncpark commented on src/subscribe.rs
>              error!("giganto connection error occur : {}", e);
giganto connection error occur => Giganto connection error occur

2023-04-21 07:55 UTC, sehkone approved these changes

2023-05-02 20:37 UTC, msk approved these changes

2023-05-03 01:39 UTC, syncpark commented
@BLYKIM rebase 해주세요.

2023-05-03 04:10 UTC, syncpark approved these changes

2023-05-03 04:10 UTC, merged